import { expect, test } from "@playwright/test";
import { readCellMetrics, readCellProbe } from "./helpers/cell-probe";

test("Dialog uses Canvas input, named semantics and focus restoration", async ({ page }) => {
  await page.goto("/exp/web-tui/#/components/dialog");
  const surface = page.locator('[data-cell-probe="component-dialog"]');
  const canvas = surface.locator("canvas").first();
  await canvas.scrollIntoViewIfNeeded();
  const metrics = await readCellMetrics(surface);
  const probe = await readCellProbe(surface);
  const cell = probe.cells.find((cell) => cell.ownerId === "dialog-open")!;
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.click(bounds.x + (cell.x + 0.5) * metrics.cellWidth, bounds.y + (cell.y + 0.5) * metrics.cellHeight);
  const dialog = surface.getByRole("dialog", { name: "Continue?", exact: true });
  await expect(dialog).toBeAttached();
  await expect(dialog).toHaveAttribute("aria-modal", "true");
  await expect(dialog).toHaveAccessibleDescription("This is a preview confirmation.");
  const cancel = surface.getByRole("button", { name: "Cancel", exact: true });
  await expect(surface).toHaveAttribute("data-cell-focused", "dialog-cancel");
  await page.keyboard.press("Tab");
  await expect(surface.getByRole("button", { name: "Continue", exact: true })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(cancel).toBeFocused();
  expect((await readCellProbe(surface)).text).toContain("Continue?");
  expect((await readCellProbe(surface)).text).toContain("└──────────────────────────────────┘");
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await expect(surface.getByRole("button", { name: "Open dialog", exact: true })).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(cancel).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(dialog).toHaveCount(0);
});

test("Dialog outside-click policy and nonmodal focus exit are independent", async ({ page }) => {
  await page.goto("/exp/web-tui/#/components/dialog");
  const surface = page.locator('[data-cell-probe="component-dialog"]');
  const open = surface.getByRole("button", { name: "Open dialog", exact: true });
  await surface.getByRole("checkbox", { name: "closeOnOutsideClick", exact: true }).evaluate((element: HTMLElement) => element.click());
  await open.evaluate((element: HTMLElement) => element.click());
  const dialog = surface.getByRole("dialog", { name: "Continue?", exact: true });
  await expect(dialog).toBeAttached();
  const bounds = (await surface.locator("canvas").first().boundingBox())!;
  await page.mouse.click(bounds.x + 2, bounds.y + 2);
  await expect(dialog).toBeAttached();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await surface.getByRole("checkbox", { name: "modal", exact: true }).evaluate((element: HTMLElement) => element.click());
  await open.evaluate((element: HTMLElement) => element.click());
  await expect(dialog).not.toHaveAttribute("aria-modal", "true");
  await surface.getByRole("button", { name: "Continue", exact: true }).focus();
  await page.keyboard.press("Tab");
  await expect(surface.getByRole("checkbox", { name: "modal", exact: true })).toBeFocused();
  await expect(dialog).toBeAttached();
  await page.keyboard.press("Escape");
  await expect(dialog).toHaveCount(0);
  await surface.getByRole("checkbox", { name: "closeOnOutsideClick", exact: true }).evaluate((element: HTMLElement) => element.click());
  await open.evaluate((element: HTMLElement) => element.click());
  await expect(dialog).toBeAttached();
  await page.mouse.click(bounds.x + 2, bounds.y + 2);
  await expect(dialog).toHaveCount(0);
});
