import { expect, test } from "@playwright/test";
import { readCellMetrics, readCellProbe } from "./helpers/cell-probe";

test("Accordion independently expands, preserves content, and shares keyboard and pointer feedback", async ({ page }) => {
  await page.emulateMedia({ colorScheme: "light" });
  await page.goto("/exp/web-tui/#/components/accordion");
  const surface = page.locator('[data-cell-probe="component-accordion"]');
  const general = surface.getByRole("button", { name: "General", exact: true });
  const appearance = surface.getByRole("button", { name: "Appearance", exact: true });
  await expect(general).toHaveAttribute("aria-expanded", "false");
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await expect(surface.getByRole("checkbox", { name: "Sound" })).toHaveCount(0);
  const canvas = surface.locator("canvas").first();
  await canvas.scrollIntoViewIfNeeded();
  const metrics = await readCellMetrics(surface);
  const trigger = (await readCellProbe(surface)).cells.find((cell) => cell.ownerId === "accordion-appearance-trigger" && cell.text === "▸")!;
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.click(bounds.x + (trigger.x + 0.5) * metrics.cellWidth, bounds.y + (trigger.y + 0.5) * metrics.cellHeight);
  await expect(appearance).toHaveAttribute("aria-expanded", "true");
  await expect(surface.getByRole("region", { name: "Appearance", exact: true })).toBeAttached();
  await page.keyboard.press("Home");
  await expect(general).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(general).toHaveAttribute("aria-expanded", "true");
  await expect(appearance).toHaveAttribute("aria-expanded", "true");
  await page.keyboard.press("ArrowDown");
  await expect(appearance).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(surface.getByRole("button", { name: "Theme", exact: true })).toBeFocused();
  await page.keyboard.press("Enter");
  const opened = await readCellProbe(surface);
  const popup = opened.overlays.find(({ rootId }) => rootId === "accordion-theme-content");
  expect(popup).toBeDefined();
  expect(popup!.cells).toHaveLength(popup!.bounds.width * popup!.bounds.height);
  expect(popup!.cells.every((cell) => cell.style.backgroundColor !== undefined)).toBe(true);
  expect(popup!.cells.some((cell) => cell.style.backgroundColor === "rgb(230, 230, 230)")).toBe(true);
  expect(opened.text).toContain("Dark");
  await page.keyboard.press("ArrowDown");
  await page.keyboard.press("Enter");
  await expect(surface.getByRole("listbox")).toHaveCount(0);
  await page.keyboard.press("Tab");
  const sound = surface.getByRole("checkbox", { name: "Sound", exact: true });
  await expect(sound).toBeFocused();
  await page.keyboard.press("Space");
  await expect(sound).toHaveAttribute("aria-checked", "false");
  await appearance.evaluate((element: HTMLElement) => element.click());
  await expect(appearance).toHaveAttribute("aria-expanded", "false");
  await appearance.evaluate((element: HTMLElement) => element.click());
  await expect(sound).toHaveAttribute("aria-checked", "false");
  expect((await readCellProbe(surface)).text).toContain("Light");
  await surface.getByRole("checkbox", { name: "disabled", exact: true }).evaluate((element: HTMLElement) => element.click());
  await expect(general).toHaveAttribute("aria-disabled", "true");
  await expect(sound).toHaveAttribute("aria-disabled", "true");
  await appearance.evaluate((element: HTMLElement) => element.click());
  await expect(appearance).toHaveAttribute("aria-expanded", "true");
});
