import type {
  AccordionContentProps,
  AccordionItemProps,
  AccordionProps,
  AlertProps,
  AlertDialogProps,
  BoxProps,
  BadgeProps,
  ButtonProps,
  ComboboxInputProps,
  ComboboxProps,
  DialogProps,
  ProgressProps,
  ListItemProps,
  ListProps,
  SpinnerProps,
  TooltipProps,
  RootProps,
  ScrollAreaProps,
  SeparatorProps,
  SliderProps,
  SliderThumb,
  SelectContentProps,
  SelectProps,
  SelectTriggerProps,
  TextAreaProps,
  TextInputProps,
} from "@chardesk/cell-ui";

type Expect<Condition extends true> = Condition;
type Has<Props, Key extends PropertyKey> = Key extends keyof Props ? true : false;
type Lacks<Props, Key extends PropertyKey> = Key extends keyof Props ? false : true;
type Same<Left, Right> =
  (<Value>() => Value extends Left ? 1 : 2) extends
  (<Value>() => Value extends Right ? 1 : 2) ? true : false;

type ComponentPropContract = [
  Expect<Has<RootProps, "children">>,
  Expect<Lacks<RootProps, "label">>,
  Expect<Lacks<BoxProps, "label">>,
  Expect<Same<NonNullable<AlertProps["tone"]>, "info" | "success" | "warning" | "error">>,
  Expect<Same<NonNullable<AlertProps["variant"]>, "surface" | "ghost">>,
  Expect<Same<NonNullable<AlertProps["border"]>, "none" | "square" | "rounded">>,
  Expect<Has<BoxProps, "variant">>,
  Expect<Has<BoxProps, "frame">>,
  Expect<Lacks<ButtonProps, "size">>,
  Expect<Has<ButtonProps, "style">>,
  Expect<Same<NonNullable<BadgeProps["tone"]>, "neutral" | "info" | "success" | "warning" | "error">>,
  Expect<Has<BadgeProps, "interactive">>,
  Expect<Lacks<BadgeProps, "variant">>,
  Expect<Same<NonNullable<ButtonProps["variant"]>, "solid" | "outline" | "surface" | "ghost">>,
  Expect<Lacks<AccordionProps, "label">>,
  Expect<Lacks<AccordionItemProps, "label">>,
  Expect<Has<AccordionContentProps, "label">>,
  Expect<Has<DialogProps, "label">>,
  Expect<Has<AlertDialogProps, "initialFocusId">>,
  Expect<Lacks<AlertDialogProps, "closeOnOutsideClick">>,
  Expect<Same<NonNullable<DialogProps["border"]>, "none" | "square" | "rounded">>,
  Expect<Lacks<DialogProps, "bordered">>,
  Expect<Lacks<DialogProps, "borderShape">>,
  Expect<Lacks<DialogProps, "frame">>,
  Expect<Lacks<SelectProps, "label">>,
  Expect<Has<SelectTriggerProps, "label">>,
  Expect<Has<SelectContentProps, "label">>,
  Expect<Lacks<ComboboxProps, "label">>,
  Expect<Has<ComboboxInputProps, "label">>,
  Expect<Lacks<ComboboxInputProps, "variant">>,
  Expect<Lacks<ScrollAreaProps, "label">>,
  Expect<Lacks<TextInputProps, "children">>,
  Expect<Lacks<TextAreaProps, "children">>,
  Expect<Lacks<ComboboxInputProps, "children">>,
  Expect<Has<ProgressProps, "variant">>,
  Expect<Same<NonNullable<ProgressProps["variant"]>, "solid" | "outline">>,
  Expect<Same<NonNullable<ProgressProps["number"]>, boolean>>,
  Expect<Same<NonNullable<SpinnerProps["variant"]>, "wheel" | "dots">>,
  Expect<Lacks<SpinnerProps, "size">>,
  Expect<Has<TooltipProps, "targetId">>,
  Expect<Has<TooltipProps, "text">>,
  Expect<Same<NonNullable<TooltipProps["variant"]>, "surface" | "ghost">>,
  Expect<Same<NonNullable<TooltipProps["border"]>, "none" | "square" | "rounded">>,
  Expect<Lacks<TooltipProps, "bordered">>,
  Expect<Lacks<TooltipProps, "borderShape">>,
  Expect<Lacks<TooltipProps, "frame">>,
  Expect<Same<NonNullable<SeparatorProps["variant"]>, "line" | "slash" | "double" | "dots">>,
  Expect<Lacks<ProgressProps, "size">>,
  Expect<Same<Extract<SliderProps, { value: number }>["value"], number>>,
  Expect<Same<Extract<SliderProps, { value: readonly [number, number] }>["thumbs"], readonly [SliderThumb, SliderThumb]>>,
  Expect<Lacks<typeof import("@chardesk/cell-ui"), "RangeSlider">>,
  Expect<Has<typeof import("@chardesk/cell-ui"), "List">>,
  Expect<Has<typeof import("@chardesk/cell-ui"), "Menu">>,
  Expect<Has<ListProps, "reorderable">>,
  Expect<Lacks<ListItemProps, "reorderable">>,
  Expect<Lacks<typeof import("@chardesk/cell-ui"), "Tree">>,
  Expect<Lacks<typeof import("@chardesk/cell-ui"), "Overlay">>,
];

export type { ComponentPropContract };
